services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
